application:
    spotify:
        clientId: CHANGE_IN_PRODUCTION
        clientSecret: CHANGE_IN_PRODUCTION

spring:
    application:
        name: cashback-api
    profiles:
        active: #spring.profiles.active#

server:
  port: 8080

management:
    endpoints:
        web:
            base-path: /management
            exposure:
                include: ["health"]