version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-node-browsers
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn install

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/cashback-api-0.0.1-SNAPSHOT.jar